# Generated by Django 3.2.12 on 2022-12-04 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=100)),
                ('nom_destination', models.CharField(max_length=100)),
                ('date_enregistrement', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_trajet', models.IntegerField(max_length=50)),
                ('lieu_depart', models.CharField(max_length=100)),
                ('lieu_arrivee', models.CharField(max_length=100)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('prix', models.IntegerField(max_length=100)),
                ('date_enregistrement', models.DateTimeField(auto_now=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=60)),
                ('nom_vehicule', models.CharField(max_length=50)),
                ('capacite', models.IntegerField(max_length=100)),
                ('nombre_place', models.IntegerField(max_length=100)),
                ('date_enregistrement', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.destination')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.trajet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Remise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_remise', models.IntegerField(max_length=60)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('montant', models.IntegerField(max_length=100)),
                ('statut_remise', models.BooleanField()),
                ('date_enregistrement', models.DateTimeField(auto_now=True)),
                ('trajet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.trajet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cycle_trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_colis', models.CharField(max_length=60)),
                ('lieu_depart', models.CharField(max_length=100)),
                ('lieu_arrivee', models.CharField(max_length=100)),
                ('date_depart', models.DateField()),
                ('nom_expediteur', models.CharField(max_length=100)),
                ('nom_destinataire', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('quantite', models.IntegerField(max_length=100)),
                ('poids', models.IntegerField(max_length=100)),
                ('prix_unitaire', models.IntegerField(max_length=100)),
                ('date_enregistrement', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.vehicule')),
            ],
        ),
    ]
