# Generated by Django 4.1.5 on 2023-03-16 12:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_trajet', models.CharField(max_length=50)),
                ('lieu_depart', models.CharField(default='', max_length=100)),
                ('lieu_arrivee', models.CharField(default='', max_length=100)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('prix', models.IntegerField(max_length=100)),
                ('date_enregistrement', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(default='', max_length=60)),
                ('nom_vehicule', models.CharField(default='', max_length=50)),
                ('capacite', models.IntegerField(default='')),
                ('place_restante', models.IntegerField(default=80, null=True)),
                ('type', models.CharField(default='', max_length=100)),
                ('date_enregistrement', models.DateTimeField(auto_now=True)),
                ('trajet', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.trajet')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=1)),
                ('date_depat', models.DateTimeField()),
                ('heure_depat', models.TimeField(default=datetime.datetime(2023, 3, 16, 12, 53, 31, 848947))),
                ('place', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.trajet')),
                ('vehicule', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Remise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_remise', models.IntegerField(max_length=60)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('montant', models.IntegerField(max_length=100)),
                ('statut_remise', models.BooleanField()),
                ('date_enregistrement', models.DateTimeField(auto_now=True)),
                ('trajet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.trajet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=100)),
                ('nom_destination', models.CharField(max_length=100)),
                ('date_enregistrement', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_colis', models.CharField(max_length=60)),
                ('status', models.CharField(default='', max_length=100)),
                ('date_depart', models.DateField()),
                ('nom_expediteur', models.CharField(max_length=100)),
                ('nom_destinataire', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('quantite', models.IntegerField(max_length=100)),
                ('poids', models.IntegerField(max_length=100)),
                ('prix_unitaire', models.IntegerField(max_length=100)),
                ('date_enregistrement', models.DateTimeField(auto_now=True)),
                ('trajet', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.trajet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.vehicule')),
            ],
        ),
    ]
