# Generated by Django 4.1.5 on 2023-03-13 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminPanel', '0002_auto_20221204_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('date_depat', models.DateTimeField(auto_created=True)),
                ('client', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='trajet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cycle_trajet',
        ),
        migrations.AddField(
            model_name='reservations',
            name='trajet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.trajet'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.vehicule'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
