# Generated by Django 4.1.5 on 2023-03-13 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0003_reservations_remove_vehicule_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajet',
            name='lieu_arrivee',
        ),
        migrations.RemoveField(
            model_name='trajet',
            name='lieu_depart',
        ),
        migrations.AddField(
            model_name='trajet',
            name='destination',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.destination'),
        ),
    ]
