# Generated by Django 4.1.5 on 2023-03-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0004_remove_trajet_lieu_arrivee_remove_trajet_lieu_depart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajet',
            name='destination',
        ),
        migrations.AddField(
            model_name='trajet',
            name='lieu_arrivee',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trajet',
            name='lieu_depart',
            field=models.CharField(default='', max_length=100),
        ),
    ]
