# Generated by Django 4.1.5 on 2023-03-13 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0005_remove_trajet_destination_trajet_lieu_arrivee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colis',
            name='lieu_arrivee',
        ),
        migrations.RemoveField(
            model_name='colis',
            name='lieu_depart',
        ),
        migrations.AddField(
            model_name='colis',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='colis',
            name='trajet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.trajet'),
        ),
    ]
