# Generated by Django 4.1.5 on 2023-03-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0007_remove_reservations_vehicule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='date_depat',
            field=models.TimeField(),
        ),
    ]
