# Generated by Django 4.1.5 on 2023-03-14 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0008_alter_reservations_date_depat'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='heure_depat',
            field=models.TimeField(default=datetime.datetime(2023, 3, 14, 16, 38, 24, 193121)),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='date_depat',
            field=models.DateTimeField(),
        ),
    ]
