# Generated by Django 4.1.5 on 2023-03-14 16:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminPanel', '0009_reservations_heure_depat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='client',
        ),
        migrations.AlterField(
            model_name='reservations',
            name='heure_depat',
            field=models.TimeField(default=datetime.datetime(2023, 3, 14, 16, 42, 1, 760155)),
        ),
        migrations.AddField(
            model_name='reservations',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
