# Generated by Django 4.1.5 on 2023-03-14 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0010_remove_reservations_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='heure_depat',
            field=models.TimeField(default=datetime.datetime(2023, 3, 14, 16, 50, 17, 900489)),
        ),
    ]
