# Generated by Django 4.1.5 on 2023-03-14 18:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0011_alter_reservations_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='place',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservations',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='reservations',
            name='vehicule',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.vehicule'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='place_restante',
            field=models.IntegerField(default=80, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='heure_depat',
            field=models.TimeField(default=datetime.datetime(2023, 3, 14, 18, 2, 8, 566752)),
        ),
    ]
